### ISSUE TITLE
ошибка brotli

### ISSUE THREAD

**Issue by Anton32reg** [Duff89/proxy_use_example_for_parsing#1]
'''я не давно вернулся в пайтон после долгого отсутствия, прошу простить если проблема пустяковая, но если можете, объясните причину возникновения и как её исправить'''

Пайтон скачан один, версия 311, работаю в вирт, первый раз заметил когда пытаюсь юзать прокси на uc
Ошибка говорит что нет модуля, но он есть.
Код Python:

Код Python:
`Traceback (most recent call last):

  File "D:\pycharmProjects_1\projects\olo.py", line 1, in <module>

    import brotli

  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\brotli.py", line 8, in <module>

    import _brotli

ImportError: DLL load failed while importing _brotli: Не найден указанный модуль.`
если без import brotli то:

ХОТЯ ОН ЕСТЬ, переустанавливал пару раз.

Код Python:
`Traceback (most recent call last):
  File "D:\pycharmProjects_1\projects\olo.py", line 1, in <module>
    from seleniumwire import undetected_chromedriver as uc
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 12, in <module>
    from seleniumwire.inspect import InspectRequestsMixin
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\inspect.py", line 7, in <module>
    from seleniumwire import har
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\har.py", line 12, in <module>
    from seleniumwire.thirdparty.mitmproxy.http import HTTPFlow
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\http.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import http
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import http1, http2, multipart, status_codes
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\__init__.py", line 2, in <module>
    from .read import (connection_close, expected_http_body_size, read_body, read_request, read_request_head,
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import (headers, request,
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import cookies, message, multipart
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import encoding
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in <module>
    import brotli
  File "D:\pycharmProjects_1\projects\venv\Lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: Не найден указанный модуль.`

список всех файлов при установки бротли: (все без .py)
INSTALLER
LICENSE
METADATA
RECORD
REQUESTED
top_level.txt
WHEEL

код который я использую у себя это примеры 2, 3 

мой код:

`from seleniumwire import undetected_chromedriver as uc
import time

def proxy_line(file):
    with open(file, "r+") as f:
        lines = f.readlines()
        if len(lines) > 0:
            proxy = lines[0].strip()  
            f.seek(0)  
            f.writelines(lines[1:])  
            f.truncate() 
            return proxy
        else:
            return None

options = uc.ChromeOptions()
options.binary_location = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
driver = uc.Chrome(options=options) #seleniumwire_options=proxy)
print(proxy)

try:
    driver.get("https://whoer.net/ru")
except Exception as ex:
    print(ex)
finally:
    time.sleep(100)
    driver.close()
    driver.quit()`

**Comment by Anton32reg** [comment]
Проблема решена
